# Eurostat - *The Rising Cost of Living in Portugal: An Analysis of Consumer Price Inflation*

In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests

print("Everything is working!")

Everything is working!

#### Wrangling HICP_MANR dataset

In [2]:
#import csv file
df_manr = pd.read_csv(r"C:\Users\Asus\Documents\DA CareerFoundry\Side Projects\inflacao-dashboard\data\raw\prc_hicp_manr.csv")

In [3]:
df_manr.head(10)

,DATAFLOW,LAST UPDATE,freq,unit,coicop,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-01,1.7,NaN,NaN
1,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-02,1.7,NaN,NaN
2,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-03,1.4,NaN,NaN
3,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-04,2.1,NaN,NaN
4,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-05,1.3,NaN,NaN
5,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-06,1.5,NaN,NaN
6,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-07,1.1,NaN,NaN
7,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-08,1.0,NaN,NaN
8,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-09,0.9,NaN,NaN
9,ESTAT:PRC_HICP_MANR(1.0),06/02/26 23:00:00,Monthly,Annual rate of change,All-items HICP,Germany,2019-10,0.9,NaN,NaN

In [4]:
df_manr.shape

(14112, 10)

In [5]:
unique_cat = df_manr['coicop'].unique()
print(unique_cat)

<StringArray>
[                                          'All-items HICP',
                         'Food and non-alcoholic beverages',
                                                    'Bread',
                                            'Beef and veal',
                                                     'Pork',
                                                  'Poultry',
                                    'Fresh or chilled fish',
                                    'Milk, cheese and eggs',
                                                     'Eggs',
                                                   'Butter',
                                                'Olive oil',
                                               'Vegetables',
                                                 'Potatoes',
                                                'Chocolate',
                                                   'Coffee',
                                         'Wine from grapes',
                                               'Cigarettes',
                                                 'Clothing',
         'Housing, water, electricity, gas and other fuels',
                                              'Electricity',
                                                      'Gas',
                                                   'Diesel',
                                                   'Petrol',
                   'Veterinary and other services for pets',
                                                    'Books',
                          'Restaurants, cafés and the like',
 'Hairdressing salons and personal grooming establishments',
                                                   'Energy']
Length: 28, dtype: str

In [6]:
# dropping not needed columns
df_manr = df_manr.drop(df_manr.columns[[0, 1, 2, 3, 8, 9]], axis=1)  # df.columns is zero-based pd.Index

In [7]:
df_manr.head(5)

           coicop      geo TIME_PERIOD  OBS_VALUE
0  All-items HICP  Germany     2019-01        1.7
1  All-items HICP  Germany     2019-02        1.7
2  All-items HICP  Germany     2019-03        1.4
3  All-items HICP  Germany     2019-04        2.1
4  All-items HICP  Germany     2019-05        1.3

In [8]:
#renaming columns 
df_manr.rename(columns={'coicop': 'category', 'geo': 'country', 'TIME_PERIOD': 'date', 'OBS_VALUE': 'homologous_inflation'}, inplace=True)

In [9]:
print(df_manr)

             category   country     date  homologous_inflation
0      All-items HICP   Germany  2019-01                   1.7
1      All-items HICP   Germany  2019-02                   1.7
2      All-items HICP   Germany  2019-03                   1.4
3      All-items HICP   Germany  2019-04                   2.1
4      All-items HICP   Germany  2019-05                   1.3
...               ...       ...      ...                   ...
14107          Energy  Portugal  2025-08                  -0.1
14108          Energy  Portugal  2025-09                   0.4
14109          Energy  Portugal  2025-10                  -1.2
14110          Energy  Portugal  2025-11                  -0.7
14111          Energy  Portugal  2025-12                  -2.4

[14112 rows x 4 columns]

#### Wrangling HICP_INW dataset

In [10]:
#import csv file
df_inw = pd.read_csv(r"C:\Users\Asus\Documents\DA CareerFoundry\Side Projects\inflacao-dashboard\data\raw\prc_hicp_inw.csv")

In [11]:
df_inw.head(5)

,DATAFLOW,LAST UPDATE,freq,coicop,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:PRC_HICP_INW(1.0),20/08/25 11:00:00,Annual,All-items HICP,Germany,2019,1000.0,NaN,NaN
1,ESTAT:PRC_HICP_INW(1.0),20/08/25 11:00:00,Annual,All-items HICP,Germany,2020,1000.0,NaN,NaN
2,ESTAT:PRC_HICP_INW(1.0),20/08/25 11:00:00,Annual,All-items HICP,Germany,2021,1000.0,NaN,NaN
3,ESTAT:PRC_HICP_INW(1.0),20/08/25 11:00:00,Annual,All-items HICP,Germany,2022,1000.0,NaN,NaN
4,ESTAT:PRC_HICP_INW(1.0),20/08/25 11:00:00,Annual,All-items HICP,Germany,2023,1000.0,NaN,NaN

In [12]:
df_inw.shape

(1176, 9)

In [13]:
unique_cat_2 = df_inw['coicop'].unique()
print(unique_cat_2)

<StringArray>
[                                          'All-items HICP',
                         'Food and non-alcoholic beverages',
                                                    'Bread',
                                            'Beef and veal',
                                                     'Pork',
                                                  'Poultry',
                                    'Fresh or chilled fish',
                                    'Milk, cheese and eggs',
                                                     'Eggs',
                                                   'Butter',
                                                'Olive oil',
                                               'Vegetables',
                                                 'Potatoes',
                                                'Chocolate',
                                                   'Coffee',
                                         'Wine from grapes',
                                               'Cigarettes',
                                                 'Clothing',
         'Housing, water, electricity, gas and other fuels',
                                              'Electricity',
                                                      'Gas',
                                                   'Diesel',
                                                   'Petrol',
                   'Veterinary and other services for pets',
                                                    'Books',
                          'Restaurants, cafés and the like',
 'Hairdressing salons and personal grooming establishments',
                                                   'Energy']
Length: 28, dtype: str

In [14]:
# dropping not needed columns
df_inw = df_inw.drop(df_inw.columns[[0, 1, 2, 7, 8]], axis=1)  # df.columns is zero-based pd.Index

In [15]:
df_inw.head(5)

           coicop      geo  TIME_PERIOD  OBS_VALUE
0  All-items HICP  Germany         2019     1000.0
1  All-items HICP  Germany         2020     1000.0
2  All-items HICP  Germany         2021     1000.0
3  All-items HICP  Germany         2022     1000.0
4  All-items HICP  Germany         2023     1000.0

In [16]:
#renaming columns 
df_inw.rename(columns={'coicop': 'category', 'geo': 'country', 'TIME_PERIOD': 'date', 'OBS_VALUE': 'item_weight'}, inplace=True)

In [18]:
print(df_inw)

            category   country  date  item_weight
0     All-items HICP   Germany  2019      1000.00
1     All-items HICP   Germany  2020      1000.00
2     All-items HICP   Germany  2021      1000.00
3     All-items HICP   Germany  2022      1000.00
4     All-items HICP   Germany  2023      1000.00
...              ...       ...   ...          ...
1171          Energy  Portugal  2021        79.00
1172          Energy  Portugal  2022        80.23
1173          Energy  Portugal  2023        80.58
1174          Energy  Portugal  2024        58.42
1175          Energy  Portugal  2025        70.86

[1176 rows x 4 columns]

Check datatypes on each dataset before merging

#### Wrangling HIP_Q dataset

In [19]:
#import csv file
df_q = pd.read_csv(r"C:\Users\Asus\Documents\DA CareerFoundry\Side Projects\inflacao-dashboard\data\raw\prc_hpi_q.csv")

In [20]:
df_q.head(5)

,DATAFLOW,LAST UPDATE,freq,purchase,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:PRC_HPI_Q(1.0),02/07/26 11:00:00,Quarterly,Purchases of existing dwellings,Quarterly rate of change,Germany,2019-Q1,0.0,NaN,NaN
1,ESTAT:PRC_HPI_Q(1.0),02/07/26 11:00:00,Quarterly,Purchases of existing dwellings,Quarterly rate of change,Germany,2019-Q2,2.8,NaN,NaN
2,ESTAT:PRC_HPI_Q(1.0),02/07/26 11:00:00,Quarterly,Purchases of existing dwellings,Quarterly rate of change,Germany,2019-Q3,1.3,NaN,NaN
3,ESTAT:PRC_HPI_Q(1.0),02/07/26 11:00:00,Quarterly,Purchases of existing dwellings,Quarterly rate of change,Germany,2019-Q4,2.3,NaN,NaN
4,ESTAT:PRC_HPI_Q(1.0),02/07/26 11:00:00,Quarterly,Purchases of existing dwellings,Quarterly rate of change,Germany,2020-Q1,1.1,NaN,NaN

In [21]:
df_q.shape

(522, 10)

In [22]:
# dropping not needed columns
df_q = df_q.drop(df_q.columns[[0, 1, 2, 4, 8, 9]], axis=1)  # df.columns is zero-based pd.Index

In [23]:
df_q.head(5)

                          purchase      geo TIME_PERIOD  OBS_VALUE
0  Purchases of existing dwellings  Germany     2019-Q1        0.0
1  Purchases of existing dwellings  Germany     2019-Q2        2.8
2  Purchases of existing dwellings  Germany     2019-Q3        1.3
3  Purchases of existing dwellings  Germany     2019-Q4        2.3
4  Purchases of existing dwellings  Germany     2020-Q1        1.1

In [24]:
#renaming columns 
df_q.rename(columns={'geo': 'country', 'TIME_PERIOD': 'date', 'OBS_VALUE': 'house_price_growth_quarterly'}, inplace=True)

In [25]:
print(df_q)

                            purchase   country     date  \
0    Purchases of existing dwellings   Germany  2019-Q1
1    Purchases of existing dwellings   Germany  2019-Q2
2    Purchases of existing dwellings   Germany  2019-Q3
3    Purchases of existing dwellings   Germany  2019-Q4
4    Purchases of existing dwellings   Germany  2020-Q1
..                               ...       ...      ...
517                            Total  Portugal  2025-Q1
518                            Total  Portugal  2025-Q2
519                            Total  Portugal  2025-Q3
520                            Total  Portugal  2025-Q4
521                            Total  Portugal  2026-Q1

     house_price_growth_quarterly
0                             0.0
1                             2.8
2                             1.3
3                             2.3
4                             1.1
..                            ...
517                           4.8
518                           4.8
519                           4.1
520                           4.0
521                           3.8

[522 rows x 4 columns]

In [27]:
df_manr.info()

<class 'pandas.DataFrame'>
RangeIndex: 14112 entries, 0 to 14111
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   category              14112 non-null  str
 1   country               14112 non-null  str
 2   date                  14112 non-null  str
 3   homologous_inflation  14112 non-null  float64
dtypes: float64(1), str(3)
memory usage: 441.1 KB

In [28]:
df_inw.info()

<class 'pandas.DataFrame'>
RangeIndex: 1176 entries, 0 to 1175
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   category     1176 non-null   str
 1   country      1176 non-null   str
 2   date         1176 non-null   int64
 3   item_weight  1176 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 36.9 KB

In [29]:
df_q.info()

<class 'pandas.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   purchase                      522 non-null    str
 1   country                       522 non-null    str
 2   date                          522 non-null    str
 3   house_price_growth_quarterly  522 non-null    float64
dtypes: float64(1), str(3)
memory usage: 16.4 KB

Changing the data types of date from str and int64 to datetime:

In [31]:
#MANR
df_manr["date"] = pd.to_datetime(df_manr["date"], format="%Y-%m")
df_manr["homologous_inflation"] = pd.to_numeric(df_manr["homologous_inflation"])

#item weights
df_inw["date"] = pd.to_numeric(df_inw["date"]).astype("int16")
df_inw["item_weight"] = pd.to_numeric(df_inw["item_weight"])

#HPI
df_q["date"] = pd.PeriodIndex(df_q["date"], freq="Q")
df_q["house_price_growth_quarterly"] = pd.to_numeric(df_q["house_price_growth_quarterly"])

In [32]:
#creating a key called 'year' on df_manr, for later merge with df_inw:
df_manr["year"] = df_manr["date"].dt.year
df_inw = df_inw.rename(columns={"date": "year"})

In [37]:
#exporting wrangled dataframes:
df_manr.to_csv('hicp_manr_wrangled.csv', index = False)

df_inw.to_csv('hicp_inw_wrangled.csv', index = False)

df_q.to_csv('hpi_q_wrangled.csv', index = False)

#### Merging dataframes

In [33]:
hicp = df_manr.merge(
    df_inw[["country", "category", "year", "item_weight"]],
    on=["country", "category", "year"],
    how="left",
    validate="m:1",
    indicator=True)

assert (hicp["_merge"] == "both").all()
hicp = hicp.drop(columns="_merge")

In [34]:
hicp.head()

         category  country       date  homologous_inflation  year  item_weight
0  All-items HICP  Germany 2019-01-01                   1.7  2019       1000.0
1  All-items HICP  Germany 2019-02-01                   1.7  2019       1000.0
2  All-items HICP  Germany 2019-03-01                   1.4  2019       1000.0
3  All-items HICP  Germany 2019-04-01                   2.1  2019       1000.0
4  All-items HICP  Germany 2019-05-01                   1.3  2019       1000.0

In [35]:
hicp.shape

(14112, 6)

In [36]:
hicp.info()

<class 'pandas.DataFrame'>
RangeIndex: 14112 entries, 0 to 14111
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   category              14112 non-null  str
 1   country               14112 non-null  str
 2   date                  14112 non-null  datetime64[us]
 3   homologous_inflation  14112 non-null  float64
 4   year                  14112 non-null  int32
 5   item_weight           14112 non-null  float64
dtypes: datetime64[us](1), float64(2), int32(1), str(2)
memory usage: 606.5 KB

In [38]:
#exporting merged dataframe:
hicp.to_csv('hicp_merged.csv', index = False)